stages:
- build
- test

create_file:
  image: alpine
  stage: build
  script:
  - echo "we are building"
  - mkdir build
  - touch build/somefile.txt
  artifacts:
    paths:
    - build/

test_job:
  image: alpine
  stage: test
  script:
  - test -f build/somefile.txt
